name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-distribution: "temurin"
          java-version: "21"

      - name: Kill the previous process if exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo fuser -k 8082/tcp || echo "No process running on port 8082"

      - name: Install dependencies and build
        run: mvn install -DskipTests

      - name: Create the folder hackathon-dwi
        run: mkdir hackathon-dwi

      - name: Move war to hackathon-dwi
        run: mv target/*.war hackathon-dwi

      - name: Copy the hackathon-dwi to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: hackathon-dwi
          target: /home/ubuntu

      - name: Update the war file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/hackathon-dwi
            sudo nohup java -jar *.war \
                --spring.profiles.active=prod \
                --spring.datasource.url=${{ secrets.DB_URL }} \
                --spring.datasource.username=${{ secrets.DB_USERNAME }} \
                --spring.datasource.password=${{ secrets.DB_PASSWORD }} \
                --server.ssl.key-store=${{ secrets.SSL_KEYSTORE }} \
                --server.ssl.key-store-type=${{ secrets.SSL_TYPE }} \
                --server.ssl.key-alias=${{ secrets.SSL_ALIAS }} \
                --server.port=8082 \
                --server.ssl.key-password=${{ secrets.SSL_PASSWORD }} \
                --server.ssl.key-store-password=${{ secrets.SSL_PASSWORD }} \
                > output.log 2>&1 &
